config/routes.rb
Rails.application.routes.draw do
  get '/', to: "search#search_window"
  get 'search', to: "search#search"
  get 'search/result/:id', to: "search#result", as: 'search_result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/api_calls_controller.rb
class ApiCallsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  require 'kaminari'
  
  def search_window
    #search_windowは別のレイアウトを使用する。
    render layout: "search_window"
  end

  def search
    require 'nokogiri'
    require 'uri'

    keyword = URI.encode_www_form_component(params[:keyword])
    begin
    raw_response = Faraday.get "http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?key=de7e8ea5ccd50a30&lat=#{params[:lat]}&lng=#{params[:lng]}&range=#{params[:range]}&keyword=#{keyword}&count=20"
    #nokogiriによってXMLデータをRubyのハッシュ化させる
    if raw_response.success?
    doc = Nokogiri::XML(raw_response.body)
    data = Hash.from_xml(doc.to_s)

    #ハッシュにされたデータから表示したいデータを抽出し、配列に入れる。
    @results = []
    data['results']['shop'].each do |d|
      @results << {
        id: d['id'],
        name: d['name'],
        access: d['access'],
        genre: d['genre']['name'],
        logo: d['logo_image'],
        open: d['open']
      }
    end

    @posts = Kaminari.paginate_array(@results).page(params[:page] || 1).per(5)

    #店が見つからなかった場合、またはほかのエラーが発生した場合、エラーページへ飛ぶ。
    else
      render 'search/error' 
    end
  rescue Faraday::ConnectionFailed => e
      render 'search/error'
    rescue => e
      render 'search/error'
  end


  def result
        # ここで詳細ページに表示するデータを準備する
        raw_response = Faraday.get "http://webservice.recruit.co.jp/hotpepper/gourmet/v1/?key=de7e8ea5ccd50a30&id=#{params[:id]}"
        doc = Nokogiri::XML(raw_response.body)
        data = Hash.from_xml(doc.to_s)

        @result = {
          id: data['results']['shop']['id'],
          name: data['results']['shop']['name'],
          access: data['results']['shop']['access'],
          logo: data['results']['shop']['logo_image'],
          genre: data['results']['shop']['genre']['name'],
          open: data['results']['shop']['open'],
          catch: data['results']['shop']['genre']['catch'],
          photo: data['results']['shop']['photo']['pc']['l'],
          address: data['results']['shop']['address'],
          budget_average: data['results']['shop']['budget']['average']
        }
      end
    end
    end

app/helpers/api_calls_helper.rb
module ApiCallsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kensaku_helper.rb
module KensakuHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>レストラン探します</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  
        <div id="left-side">

        </div>

    <body id="main">
      <header id="header">
        <nav>
          <%= link_to image_tag('MiniLogo.PNG', class: "logo"), '/' %>
        </nav>
      </header>

      <main id="main-contents">
        <%= yield %>
      </main>  
    </body>

      <div id="right-side">
       </div>
</html>

app/views/layouts/search_window.html.erb
<!DOCTYPE html>
<html>
  <%= javascript_include_tag 'packs/geolocation' %>
  <head>
    <title>レストラン探します</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "top" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="main">

  <header id="header">
    <%= image_tag "logo.png", class: "images" %>
  </header>
  
  <div id="left-side">

  </div>
  
  <div class="search_window">
  <%#localをtrueにすることによって非同期処理でなくしている %>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%#フォームの作成、位置情報をJavaScriptから受け取り、フォームで送信する仕組みにしている。 %>
      <%= f.hidden_field :lat, id: "latitudeValue", class: "geolocation_form" %><br>
      <%= f.hidden_field :lng, id: "longitudeValue", class: "geolocation_form" %>
      <%= label_tag(:keyword, "レストラン検索") %>
      <%= check_box_tag(:keyword, 'レストラン', true) %>
      <%= f.select :range, [['半径300m付近', 1], ['半径500m付近', 2], ['半径1km付近', 3], ['半径2km付近', 4]] %>
      <%= f.submit "検索"%>
    <% end %>
  </div>
  </body>

  <div id ="right-side">
  </div>
</html>

app/views/result/result.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>レストラン探します</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if @results.present? %>
        <% @results.each do |d| %>
          <div>
            <h2><%= d[:name] %></h2>
            <p><%= d[:access] %></p>
    <% end %>
    </div>
    </div>
  </body>
</html>

app/views/search/application.html.erb
<!DOCTYPE html>
<html>
  <%= javascript_include_tag 'packs/geolocation' %>
  <head>
    <title>レストラン探します</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "top", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= image_tag "logo.png", class: 'images' %>
  <div class="container">
  <%#localをtrueにすることによって非同期処理でなくしている %>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%#フォームの作成、位置情報をJavaScriptから受け取り、フォームで送信する仕組みにしている。 %>
      
      <%= f.text_field :lat, id: "latitudeValue", class: "geolocation_form" %><br>
      <%= f.text_field :lng, id: "longitudeValue", class: "geolocation_form" %>
      <%= f.select :range, [['半径300m付近', 1], ['半径500m付近', 2], ['半径1km付近', 3], ['半径2km付近', 4]] %>
      <%= f.submit "検索"%>
    <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/search/error.html.erb
<%# エラー画面 %>
<h1>
    検索結果が見つからなかったか、そのほかのエラーが発生しました。<br>
    ヒント：検索範囲を広げて検索してみてください。
</h1>

<p>
    <%= link_to '検索ページに戻る', '/' %>
</p>

app/views/search/result.html.erb
<%= stylesheet_link_tag "result" %>

  <%# 詳細画面のアイテム %>
  <% if @result %>
    <%# コンテンツを二つに分け、レイアウトを作る。%>
    <div id="contents">
    
      <div id="shop-detail-content">
      <%= image_tag @result[:logo] %>
      <span id="shop_name"><b><%= @result[:name] %></b></span><br>    
      <span id="shop_name">＜平均予算＞<%= @result[:budget_average] %></span><br>
      <span id="shop_genre">＜ジャンル＞<%= @result[:genre] %></span><br>
      <span id="shop_catch">＜特徴＞<%= @result[:catch] %></span><br>
      <span id="shop_open">【営業時間】<%= @result[:open] %></span>
      </div>

      <%# 下のコンテンツ %>
      <div id="photo-access-content">
        <span id="shop_photo"><%= image_tag @result[:photo] %></span><br>
        <span id="shop_access">＜アクセス＞<%= @result[:access] %></span><br>
        ＜住所＞<span id="shop_address"><%= @result[:address] %></span>
      </div>
    </div>
  <% end %>

app/views/search/search.html.erb
 <%= stylesheet_link_tag 'restaurant-list' %>

    <%# 検索結果の画面 %>
    <% @posts.each do |d| %>
    <div class="container">
      <span class="shop_name"><b><%= link_to d[:name], search_result_path(id: d[:id]) %></b></span>
      <span class="shop_access">＜アクセス＞<%= d[:access] %></span>
      <span class="shop_genre">＜ジャンル＞<%= d[:genre] %></span>
      <span class="shop_open">【営業時間】<%= d[:open] %></span>
      <span class="shop_logo"><%= image_tag d[:logo] %>
    </div>
  <% end %>
  <%= paginate @posts %>

app/views/search/search_window.html.erb
<!DOCTYPE html>
<html>
  <%= javascript_include_tag 'packs/geolocation' %>
  <head>
    <title>レストラン探します</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "top", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= image_tag "logo.png", class: "images" %>
  <div class="search_window">
  <%#localをtrueにすることによって非同期処理でなくしている %>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%#フォームの作成、位置情報をJavaScriptから受け取り、フォームで送信する仕組みにしている。 %>
      
      <%= f.text_field :lat, id: "latitudeValue", class: "geolocation_form" %><br>
      <%= f.text_field :lng, id: "longitudeValue", class: "geolocation_form" %>
      <%= f.select :range, [['半径300m付近', 1], ['半径500m付近', 2], ['半径1km付近', 3], ['半径2km付近', 4]] %>
      <%= f.submit "検索"%>
    <% end %>
  </div>
  </body>
</html>

app/views/search_home/result.html.erb
<p>
    英語ポケモンの名前:<%= @result %>
</p>

<p>
    data:<%= @data %>
</p>